CREATE TABLE IF NOT EXISTS auth (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('GUEST', 'ADMIN') DEFAULT 'GUEST',
    status INT DEFAULT 1,
    user_id INT NOT NULL
)