spring:
  application:
    name: user-service
  datasource:
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    url: jdbc:mysql://localhost:${user_db_port}/${USER_DB_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

user_db_port: 3307

grpc:
  server:
    port: 9000

server:
  port: 8000


