spring:
  application:
    name: user-service
  datasource:
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/${USER_DB_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8000


