spring:
  application:
    name: discovery-server

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: "http://localhost:8009/eureka"

server:
  port: 8009