spring:
  application:
    name: property-service
  datasource:
    username: ${PROPERTY_DB_USERNAME}
    password: ${PROPERTY_DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/${PROPERTY_DB_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8009/eureka

grpc:
  client:
    location-service:
      address: static://localhost:9011
      negotiationType: plaintext

server:
  port: 8002
