spring:
  application:
    name: location-service
  datasource:
    username: ${LOCATION_DB_USERNAME}
    password: ${LOCATION_DB_PASSWORD}
    url: jdbc:mysql://localhost:${location_db_port}/${LOCATION_DB_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  flyway:
    locations: classpath:db/migration
    enabled: true
  data:
    redis:
      host: ${LOCATION_REDIS_HOST}
      port: ${LOCATION_REDIS_PORT}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8009/eureka/

location_db_port: 3307

grpc:
  server:
    port: 9011

page:
  size: 10

redis:
  time-out: 2

server:
  port: 8011
